require 'owenbot/commands/calculate'
require 'owenbot/commands/about'
require 'owenbot/commands/help'
require 'owenbot/commands/responses'
require 'owenbot/commands/wiki'
require 'owenbot/commands/greek'
require 'owenbot/commands/unknown'
